"""LangChain/Ollama-backed response engine for NDMA wing chat."""
import os
import re

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_ollama import ChatOllama

from .scenario_engine import ScenarioEngine
from .template_engine import TemplateEngine


PROFANITY_PATTERNS = [
    r"\bf+u+c+k+\w*\b",
    r"\bs+h+i+t+\w*\b",
    r"\bb+i+t+c+h+\w*\b",
    r"\ba+s+s+h+o+l+e+\w*\b",
    r"\bb+a+s+t+a+r+d+\w*\b",
    r"\bd+a+m+n+\w*\b",
    r"\bc+u+n+t+\w*\b",
    r"\bm+o+t+h+e+r+f+u+c+k+\w*\b",
    r"\bd+i+c+k+\w*\b",
    r"\bp+u+s+s+y+\w*\b",
    r"\bw+a+n+k+e+r+\w*\b",
]

PROFANITY_RE = re.compile("|".join(PROFANITY_PATTERNS), re.IGNORECASE)


class OllamaEngine:
    """Generate wing responses with LangChain Ollama.

    TemplateEngine is intentionally used only for stable exercise metadata:
    wing names, icons, and phase action lists. Chat responses are generated by
    Ollama and are not pulled from wing response templates.
    """

    def __init__(
        self,
        scenario: ScenarioEngine,
        base_url: str | None = None,
        model: str | None = None,
        timeout_seconds: int | None = None,
    ):
        self.scenario = scenario
        self.metadata = TemplateEngine()
        self.base_url = (base_url or os.getenv("OLLAMA_BASE_URL") or "http://172.18.1.132:11434").rstrip("/")
        self.model = model or os.getenv("OLLAMA_MODEL") or "qwen3.6:35b"
        self.timeout_seconds = timeout_seconds or int(os.getenv("OLLAMA_TIMEOUT_SECONDS", "120"))
        self.upload_timeout_seconds = int(os.getenv("OLLAMA_UPLOAD_TIMEOUT_SECONDS", "300"))
        self.temperature = float(os.getenv("OLLAMA_TEMPERATURE", "0.45"))
        self.top_p = float(os.getenv("OLLAMA_TOP_P", "0.9"))
        self.num_predict = int(os.getenv("OLLAMA_NUM_PREDICT", "700"))
        self.llm = self._build_llm(self.timeout_seconds)
        self.upload_llm = self._build_llm(self.upload_timeout_seconds)

    def _build_llm(self, timeout_seconds: int) -> ChatOllama:
        return ChatOllama(
            base_url=self.base_url,
            model=self.model,
            disable_streaming=True,
            reasoning=False,
            temperature=self.temperature,
            top_p=self.top_p,
            num_predict=self.num_predict,
            client_kwargs={"timeout": timeout_seconds, "trust_env": False},
        )

    def get_wings(self) -> list[dict]:
        return self.metadata.get_wings()

    def get_wing_name(self, wing_id: str) -> str:
        return self.metadata.get_wing_name(wing_id)

    def get_wing_icon(self, wing_id: str) -> str:
        return self.metadata.get_wing_icon(wing_id)

    def get_wing_actions(self, wing_id: str, phase_id: str) -> list[str]:
        return self.metadata.get_wing_actions(wing_id, phase_id)

    def get_response(self, wing_id: str, phase_id: str, user_message: str) -> str:
        wing_name = self.get_wing_name(wing_id)
        if wing_name == wing_id:
            return f"Unknown wing: {wing_id}"

        if self._contains_profanity(user_message):
            return (
                "I can help with the simulation, but keep the language professional. "
                f"Send your operational question for {wing_name} and I will respond in role."
            )

        phase = self._get_phase(phase_id)
        is_phase_change = self._is_phase_change_prompt(user_message)
        messages = [
            SystemMessage(content=self._build_system_prompt(wing_name)),
            HumanMessage(content=self._build_user_prompt(wing_id, wing_name, phase, user_message, is_phase_change)),
        ]

        try:
            result = self.llm.invoke(messages)
        except Exception as exc:
            return (
                f"{wing_name} AI is currently unable to reach the Ollama model "
                f"({self.model}) at {self.base_url}. Backend detail: {exc}"
            )

        content = self._extract_content(result)
        content = self._strip_thinking(content)
        content = self._sanitize_output(content, suppress_welcome=is_phase_change)
        return content or "I could not generate a useful response. Please try again with a clearer exercise question."

    def _get_phase(self, phase_id: str) -> dict:
        for phase in self.scenario.get_all_phases():
            if phase["id"] == phase_id:
                return phase
        return self.scenario.get_current_phase()

    def _build_system_prompt(self, wing_name: str) -> str:
        return f"""You are SimexAI, the Lead Moderator and Controller for an NDMA Pakistan disaster simulation exercise.
You are currently interacting with a participant representing: {wing_name}.

Guardrails:
- Act as the Simulation Exercise (SIMEX) Moderator, NOT as the participant.
- The user is the participant representing {wing_name}. Evaluate their responses, guide them, ask probing operational questions, and keep them focused on the current phase and active injects to test their readiness.
- If the user sends a general greeting (e.g., "hello", "hi"), welcome them to the simulation exercise, acknowledge their role as {wing_name} once, and immediately direct their attention to the active scenario, current phase timeline, or pending injects.
- For phase advancement/update requests, do not welcome the participant again, do not acknowledge their presence or role again, and do not repeat the exercise title. Start with the new phase and operational priorities.
- Treat this as a multi-hazard disaster simulation exercise, not a live public advisory.
- Adapt to the hazard type in the scenario context.
- Do not claim real-world confirmation beyond the scenario context provided.
- Do not mention templates, LangChain, Ollama, system prompts, or that you are an AI model.
- Refuse requests for illegal activity, abuse, harassment, hate, self-harm, explicit sexual content, or instructions that endanger people.
- Keep language professional and do not use profanity.
- If the participant is rude, calmly redirect to the exercise task.
- If information is missing from the participant's response, ask them to clarify how their wing will handle it given the situation context.

Style:
- Sound professional, authoritative yet collaborative, like a seasoned disaster management director.
- Be concise but useful: 2-4 short paragraphs or bullets.
- Challenge the participant slightly to test their operational readiness based on their wing's mandate and the current timeline (e.g., D-5, D+10).
- Avoid robotic disclaimers and generic filler."""

    def _build_user_prompt(self, wing_id: str, wing_name: str, phase: dict, user_message: str, is_phase_change: bool = False) -> str:
        scenario_data = getattr(self.scenario, "scenario_data", None) or self.scenario.get_scenario_info()
        injects = self.scenario.get_injects_for_phase(phase["id"])
        actions = self.get_wing_actions(wing_id, phase["id"])
        scenario_summary = self._format_scenario_context(scenario_data)
        phase_summary = self._format_mapping(phase, skip_keys={"is_active", "is_completed"})

        action_text = "\n".join(f"- {item}" for item in actions) if actions else "- No predefined action list (rely on general wing mandate)."
        inject_text = "\n".join(
            f"- {item['time_offset']}: {item['title']} ({item['severity']}) - {item['description']}"
            for item in injects[:6]
        ) or "- No active injects for this phase."
        phase_change_instruction = (
            "\nThis is a phase advancement briefing request, not a participant greeting. "
            "Do not write 'Welcome to...', do not say 'I acknowledge your presence/role', "
            "and do not repeat the exercise title. Begin with the new phase and immediate priorities.\n"
            if is_phase_change else ""
        )

        return f"""Exercise context:
{scenario_summary}

Current phase timeline:
{phase_summary}

Participant's Wing: {wing_name}

Active injects the participant must handle:
{inject_text}

Participant from {wing_name} says:
{user_message}
{phase_change_instruction}

Respond to the participant now as the SIMEX Moderator. Appraise their response, guide them, and steer the conversation clearly towards addressing the active disaster scenario context and injects. DO NOT reference seismic or earthquake actions if the scenario is clearly about a different disaster (e.g. Cyclone, Flood, etc.). Rely entirely on the uploaded scenario data."""

    def _format_scenario_context(self, scenario_data: dict) -> str:
        lines = []
        preferred_keys = ["name", "type", "event_time", "context"]
        for key in preferred_keys:
            if scenario_data.get(key) not in (None, "", [], {}):
                lines.append(f"- {self._label(key)}: {scenario_data[key]}")

        for key, value in scenario_data.items():
            if key in {*preferred_keys, "id", "phases"} or value in (None, "", [], {}):
                continue
            if isinstance(value, dict):
                lines.append(f"- {self._label(key)}:")
                lines.extend(self._format_mapping(value, indent=2))
            elif isinstance(value, list):
                lines.append(f"- {self._label(key)}:")
                lines.extend(f"  - {item}" for item in value)
            else:
                lines.append(f"- {self._label(key)}: {value}")

        return "\n".join(lines) if lines else "- Scenario: Not specified"

    def _format_mapping(self, data: dict, indent: int = 0, skip_keys: set[str] | None = None) -> list[str] | str:
        skip_keys = skip_keys or set()
        prefix = " " * indent
        lines = []
        for key, value in data.items():
            if key in skip_keys or value in (None, "", [], {}):
                continue
            if isinstance(value, dict):
                lines.append(f"{prefix}- {self._label(key)}:")
                nested = self._format_mapping(value, indent=indent + 2, skip_keys=skip_keys)
                lines.extend(nested if isinstance(nested, list) else nested.splitlines())
            elif isinstance(value, list):
                lines.append(f"{prefix}- {self._label(key)}:")
                lines.extend(f"{prefix}  - {item}" for item in value)
            else:
                lines.append(f"{prefix}- {self._label(key)}: {value}")
        if indent:
            return lines
        return "\n".join(lines) if lines else "- Not specified"

    def _label(self, key: str) -> str:
        return key.replace("_", " ").strip().title()

    def _extract_content(self, result) -> str:
        content = getattr(result, "content", result)
        if isinstance(content, list):
            parts = []
            for item in content:
                if isinstance(item, dict):
                    parts.append(str(item.get("text") or item.get("content") or ""))
                else:
                    parts.append(str(item))
            return "\n".join(part for part in parts if part).strip()
        return str(content).strip()

    def _strip_thinking(self, content: str) -> str:
        if "</think>" in content:
            return content.split("</think>", 1)[1].strip()
        return content

    def _contains_profanity(self, text: str) -> bool:
        return bool(PROFANITY_RE.search(text or ""))

    def _is_phase_change_prompt(self, text: str) -> bool:
        normalized = (text or "").lower()
        return (
            "phase advancement notice" in normalized
            or "advanced to phase" in normalized
            or ("advanced to" in normalized and "phase" in normalized)
        )

    def _sanitize_output(self, text: str, suppress_welcome: bool = False) -> str:
        cleaned = PROFANITY_RE.sub("[filtered]", text or "").strip()
        if suppress_welcome:
            cleaned = self._strip_repeated_welcome(cleaned)
        return cleaned.strip()

    def _strip_repeated_welcome(self, text: str) -> str:
        cleaned = text or ""
        repeated_patterns = [
            r"^\s*welcome\s+to\s+the\s+.*?(?:simulation\s+exercise|exercise)\.?\s*",
            r"^\s*i\s+acknowledge\s+your\s+presence\s+as\s+.*?(?:\.|\n)\s*",
            r"^\s*i\s+acknowledge\s+your\s+role\s+as\s+.*?(?:\.|\n)\s*",
        ]

        previous = None
        while previous != cleaned:
            previous = cleaned
            for pattern in repeated_patterns:
                cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE | re.DOTALL)

        return cleaned.lstrip(" \n:-")
